"""Check functions for the Lab 5 tasks.
"""

import math
import traceback

import numpy as np

from .world import DIRECTIONS, Maze, Trajectory

# ----------------------------------------------------------------------
# expected values: regenerated by instructor-lab5/make_expected.py
# ----------------------------------------------------------------------

EXPECTED = {
    'predict_uniform_north': {
        '(1, 1)': 0.06,
        '(3, 4)': 0.0333333333,
        '(5, 8)': 0.0066666667},
    'update_uniform_1010': {
        'top': (1, 2),
        'top_probability': 0.1143230528,
        '(1, 2)': 0.1143230528,
        '(3, 4)': 0.0014113957,
        '(5, 1)': 0.0014113957},
    'fixture': {
        'seed': 7,
        'steps': 12,
        'cells': [(5, 7), (5, 7), (5, 8), (5, 7), (5, 7), (5, 6), (5, 5),
                  (5, 4), (4, 4), (4, 5), (4, 5), (4, 4), (4, 4)],
        'actions': ['south', 'south', 'west', 'south', 'west', 'west',
                    'north', 'north', 'east', 'east', 'west', 'west'],
        'readings': [(1, 0, 1, 0), (1, 0, 1, 0), (0, 1, 1, 0), (1, 1, 0, 0),
                     (1, 0, 1, 0), (0, 0, 1, 0), (1, 0, 1, 0), (0, 0, 1, 0),
                     (0, 0, 0, 1), (1, 1, 0, 0), (0, 1, 0, 0), (0, 0, 0, 1),
                     (1, 0, 0, 1)]},
    'filter_fixture': {
        'length': 13,
        'first_top': (1, 2),
        'first_top_probability': 0.1143230528,
        'map_cells': [(1, 2), (1, 3), (5, 8), (5, 7), (5, 7), (5, 5), (5, 6),
                      (5, 5), (4, 4), (4, 5), (4, 5), (4, 4), (4, 4)],
        'p_truth': [0.1143230528, 0.1226651366, 0.4532784847, 0.2887825856,
                    0.467591332, 0.2367149839, 0.106011455, 0.1545417067,
                    0.9371250445, 0.9755258664, 0.9821022793, 0.9821576036,
                    0.9803562051]},
    'viterbi_fixture': {
        'log_probability': -28.7821143234},
}

TOLERANCE = 1e-6


# ----------------------------------------------------------------------
# printing
# ----------------------------------------------------------------------


def passed(name, detail):
    print("✅ " + name + ": " + detail)
    return True


def not_written_yet(name):
    print("⏳ " + name + " is not implemented yet. This is where you start!")
    return False


def failed(name, lines, hint):
    print("❌ " + name + ":")
    for line in lines:
        print("   " + line)
    print("   💡 " + hint)
    return False


def crashed(name, error, verbose):
    if verbose:
        traceback.print_exception(type(error), error, error.__traceback__)
    print("❌ " + name + " raised " + type(error).__name__ + ": " + str(error))
    where = student_line(error)
    if where:
        print("   " + where)
    if not verbose:
        print("   💡 Re-run this check with verbose=True for the full traceback.")
    return False


def student_line(error):
    """A short pointer to the deepest line of student code, if there is one."""
    frames = []
    for frame in traceback.extract_tb(error.__traceback__):
        if frame.filename and "lab5kit" not in frame.filename:
            frames.append(frame)
    if not frames or not frames[-1].line:
        return ""
    return "your line " + str(frames[-1].lineno) + ": " + frames[-1].line.strip()


# ----------------------------------------------------------------------
# shared fixtures
# ----------------------------------------------------------------------


def standard_maze():
    """The maze every check uses: epsilon 0.1, p_move 0.8."""
    return Maze()


def fixture_trajectory():
    """The fixed trajectory the filter checks run on.

    Rebuilt from the recorded cells, actions and readings rather than
    simulated, so it cannot drift if the random number generator changes.
    """
    recorded = EXPECTED["fixture"]
    return Trajectory(
        cells=[tuple(cell) for cell in recorded["cells"]],
        actions=list(recorded["actions"]),
        readings=[tuple(reading) for reading in recorded["readings"]],
    )


def belief_problems(world, belief, label="the belief"):
    """Everything structurally wrong with a returned belief, as message lines."""
    lines = []
    if not isinstance(belief, dict):
        return [f"{label} should be a dictionary of cell -> probability, "
                f"but it is a {type(belief).__name__}"]

    expected_keys = set(world.cells)
    keys = set(belief)
    missing = sorted(expected_keys - keys)
    extra = sorted(keys - expected_keys)
    if missing:
        lines.append(f"{label} is missing {len(missing)} free cells, "
                     f"starting with {missing[:3]}")
    if extra:
        walls = [cell for cell in extra if cell in world.walls]
        if walls:
            lines.append(f"{label} has entries for walls: {walls[:3]}. "
                         "The robot cannot be inside a wall.")
        else:
            lines.append(f"{label} has keys that are not cells of this maze: "
                         f"{extra[:3]}")
    for cell, probability in belief.items():
        if not isinstance(probability, (int, float, np.floating)):
            lines.append(f"{label}[{cell}] is a {type(probability).__name__}, "
                         "not a number")
            break
        if probability < -TOLERANCE:
            lines.append(f"{label}[{cell}] is {probability:.6f}, and a "
                         "probability cannot be negative")
            break
    return lines


def sums_to_one(belief):
    return abs(sum(belief.values()) - 1.0) <= 1e-9


def describe_model(moves):
    """A motion model's row, without the floating-point dust."""
    return ", ".join(f"{cell} {probability:.2f}"
                     for cell, probability in sorted(moves.items()))


def describe_top(belief, count=3):
    """The most likely few cells, as a readable string."""
    ordered = sorted(belief.items(), key=lambda pair: (-pair[1], pair[0]))
    return ", ".join(f"{cell} {probability:.4f}"
                     for cell, probability in ordered[:count])


# ----------------------------------------------------------------------
# Task 1: the sensor model
# ----------------------------------------------------------------------


def check_sensor_likelihood(sensor_likelihood, verbose=False):
    """Check a sensor_likelihood(world, reading, cell) implementation."""
    name = "sensor_likelihood"
    try:
        world = standard_maze()
        cell = (1, 1)
        truth = world.signature(cell)          # (1, 0, 0, 1)

        perfect = sensor_likelihood(world, truth, cell)
        if not isinstance(perfect, (int, float, np.floating)):
            return failed(
                name,
                [f"it returned a {type(perfect).__name__}, not a number"],
                "Return a single probability: the product of four factors.")
        if abs(perfect - 0.9 ** 4) > TOLERANCE:
            return failed(
                name,
                [f"in cell {cell} a perfect sonar would read {truth}.",
                 f"P({truth} | {cell}) came out as {perfect:.6f}, "
                 f"expected {0.9 ** 4:.6f}"],
                "Every beam agrees with the truth here, so every factor is "
                "1 - epsilon = 0.9, and the answer is 0.9 ** 4.")

        one_wrong = (1 - truth[0],) + tuple(truth[1:])
        got = sensor_likelihood(world, one_wrong, cell)
        want = 0.9 ** 3 * 0.1
        if abs(got - want) > TOLERANCE:
            detail = [f"the north beam of {one_wrong} disagrees with the "
                      f"truth {truth} in cell {cell}, and the other three agree.",
                      f"got {got:.6f}, expected {want:.6f}"]
            if abs(got - 0.1 ** 4) <= TOLERANCE:
                detail.append("it looks like every factor came out as epsilon: "
                              "check which way round your comparison is.")
            return failed(
                name, detail,
                "One beam lying costs a factor of epsilon; the other three "
                "telling the truth each cost 1 - epsilon.")

        all_wrong = tuple(1 - bit for bit in truth)
        got = sensor_likelihood(world, all_wrong, cell)
        if abs(got - 0.1 ** 4) > TOLERANCE:
            return failed(
                name,
                [f"with all four beams wrong, got {got:.8f}, "
                 f"expected {0.1 ** 4:.8f}"],
                "This reading is possible, just unlikely: epsilon ** 4. "
                "It must not come out as 0.")

        # The noise has to be read off the world, not written into the function.
        noisy = world.variant(epsilon=0.25)
        got = sensor_likelihood(noisy, truth, cell)
        if abs(got - 0.75 ** 4) > TOLERANCE:
            return failed(
                name,
                [f"with world.epsilon = 0.25, P({truth} | {cell}) came out as "
                 f"{got:.6f}, expected {0.75 ** 4:.6f}"],
                "Use world.epsilon rather than 0.1. Part 6 hands this "
                "function a world whose sonar noise is different.")

        # Likelihoods are not a distribution over cells and must not be
        # normalized: this total is nowhere near 1.
        reading = (1, 0, 1, 0)
        total = sum(sensor_likelihood(world, reading, c) for c in world.cells)
        if abs(total - 1.0) <= TOLERANCE:
            return failed(
                name,
                [f"adding P({reading} | cell) over all 30 cells gives exactly "
                 "1.0, which means the function is dividing by the total"],
                "This is P(reading | cell), not P(cell | reading). Each cell "
                "is answered on its own, with no reference to the others. "
                "Normalizing is update's job.")

        return passed(name, f"P({truth} | {cell}) = {perfect:.4f}, "
                            f"one beam wrong {want:.4f}, "
                            f"all four wrong {0.1 ** 4:.4f}")
    except NotImplementedError:
        return not_written_yet(name)
    except Exception as error:  # noqa: BLE001 - reported to the student
        return crashed(name, error, verbose)


# ----------------------------------------------------------------------
# Task 2: the motion model
# ----------------------------------------------------------------------


def check_predict(predict, verbose=False):
    """Check a predict(world, belief, action) implementation."""
    name = "predict"
    try:
        world = standard_maze()

        # From a cell the robot knows it is in, predict must reproduce the
        # motion model exactly.
        cell = (1, 1)
        got = predict(world, world.point_belief(cell), "east")
        problems = belief_problems(world, got, "predict's result")
        if problems:
            return failed(name, problems,
                          "Return a dictionary with one entry per free "
                          "cell in world.cells, including the cells whose "
                          "probability is 0.")

        want = world.transition(cell, "east")
        for landing, probability in want.items():
            if abs(got[landing] - probability) > TOLERANCE:
                lines = [
                    f"starting certain of {cell} and driving east, the motion "
                    f"model says {describe_model(want)}.",
                    f"your belief has {landing} at {got[landing]:.6f}, "
                    f"expected {probability:.6f}",
                    f"your top cells: {describe_top(got)}",
                ]
                if abs(got[world.neighbor(cell, "east")] - 1.0) < TOLERANCE:
                    lines.append(
                        "all of the probability went to the intended cell, so "
                        "the 20% that drifts sideways is missing.")
                return failed(
                    name, lines,
                    "With all the probability on one cell, the answer is just "
                    "that cell's row of the motion model. Make sure you are "
                    "spreading mass *from* each cell *to* the cells "
                    "world.transition(cell, action) names.")

        if abs(sum(got.values()) - 1.0) > 1e-9:
            return failed(
                name,
                [f"the probabilities add up to {sum(got.values()):.6f}, not 1"],
                "Every cell's transition probabilities already add to 1, so "
                "moving cannot create or destroy belief. Check you are adding "
                "to the new belief rather than overwriting it.")

        # Driving into a wall: the robot stays, and no mass enters the wall.
        got = predict(world, world.point_belief(cell), "west")
        if abs(got[cell] - 0.9) > TOLERANCE:
            return failed(
                name,
                [f"{cell} has a wall to the west and to the north, so driving "
                 "west leaves the robot where it is 0.9 of the time "
                 "(0.8 blocked, plus 0.1 of the northward drift also blocked).",
                 f"your belief puts {got[cell]:.6f} on {cell}",
                 f"your top cells: {describe_top(got)}"],
                "world.transition already handles walls. Trust what it "
                "returns instead of working out the move yourself.")

        # A uniform belief, where every cell contributes.
        got = predict(world, world.uniform_belief(), "north")
        for key, want_value in EXPECTED["predict_uniform_north"].items():
            where = tuple(int(part) for part in key.strip("()").split(","))
            if abs(got[where] - want_value) > TOLERANCE:
                return failed(
                    name,
                    ["starting from a uniform belief and driving north, "
                     f"cell {where} should hold {want_value:.6f}, "
                     f"but it holds {got[where]:.6f}",
                     f"your top cells: {describe_top(got)}"],
                    "Mass piles up against the north wall, because a blocked "
                    "move leaves the robot in place. If your numbers are all "
                    "1/30 you are not moving anything; if the whole belief "
                    "shifted bodily north, the blocked cases are missing.")

        return passed(name, "the motion model is applied in the right "
                            "direction, walls included, and the belief still "
                            "sums to 1")
    except NotImplementedError:
        return not_written_yet(name)
    except Exception as error:  # noqa: BLE001
        return crashed(name, error, verbose)


# ----------------------------------------------------------------------
# Task 3: conditioning on a reading
# ----------------------------------------------------------------------


def check_update(update, verbose=False):
    """Check an update(world, belief, reading) implementation."""
    name = "update"
    try:
        world = standard_maze()
        reading = (1, 0, 1, 0)

        got = update(world, world.uniform_belief(), reading)
        problems = belief_problems(world, got, "update's result")
        if problems:
            return failed(name, problems,
                          "Return a dictionary with one entry per free cell.")

        if abs(sum(got.values()) - 1.0) > 1e-9:
            return failed(
                name,
                [f"the probabilities add up to {sum(got.values()):.6f}, not 1",
                 f"your top cells: {describe_top(got)}"],
                "Multiplying by the likelihood leaves a set of numbers "
                "that no longer add to 1. Divide every one of them by their "
                "total, which is P(reading).")

        expected = EXPECTED["update_uniform_1010"]
        if got[expected["top"]] < max(got.values()) - TOLERANCE:
            return failed(
                name,
                [f"after reading {reading} from a uniform belief, the most "
                 f"likely cell should be {expected['top']}",
                 f"your top cells: {describe_top(got)}"],
                "The reading reports a wall to the north, a wall to the "
                "south, and open space to the east and west, which describes "
                "a corridor running from left to right. Those cells should "
                "gain probability, and every other cell should lose it.")

        for key in ("(1, 2)", "(3, 4)", "(5, 1)"):
            where = tuple(int(part) for part in key.strip("()").split(","))
            want_value = expected[key]
            if abs(got[where] - want_value) > TOLERANCE:
                lines = [f"after reading {reading} from a uniform belief, "
                         f"cell {where} should hold {want_value:.6f}, "
                         f"but it holds {got[where]:.6f}",
                         f"your top cells: {describe_top(got)}"]
                if abs(got[where] - want_value * 30) < TOLERANCE:
                    lines.append("your number is 30 times too big: the "
                                 "division is by the total, not by the "
                                 "number of cells.")
                return failed(
                    name, lines,
                    "Each cell's new probability is its old one times "
                    "P(reading | cell), all divided by the sum of those "
                    "products. If sensor_likelihood is wrong then these "
                    "numbers cannot be right either, so run its check "
                    "first.")

        # A reading cannot move the robot.
        cell = (3, 4)
        got = update(world, world.point_belief(cell), (1, 1, 1, 1))
        if abs(got[cell] - 1.0) > TOLERANCE:
            return failed(
                name,
                [f"starting certain of {cell}, a reading of (1, 1, 1, 1) is "
                 "very surprising there, but there is nowhere else for the "
                 "robot to be, so the belief must stay at 1.0.",
                 f"your belief puts {got[cell]:.6f} on {cell}",
                 f"your top cells: {describe_top(got)}"],
                "Surprise alone does not move probability between cells. If "
                "mass has moved, the motion model has crept into update.")

        # With a perfect sonar, only the cells that match survive.
        perfect = world.variant(epsilon=0.0)
        matching = perfect.matching_cells(reading)
        got = update(perfect, perfect.uniform_belief(), reading)
        share = 1.0 / len(matching)
        for place, probability in got.items():
            want_value = share if place in matching else 0.0
            if abs(probability - want_value) > TOLERANCE:
                return failed(
                    name,
                    [f"with world.epsilon = 0 the reading {reading} rules out "
                     f"every cell but {len(matching)} of them, which should "
                     f"then share the belief equally at {share:.6f} each.",
                     f"cell {place} holds {probability:.6f}, "
                     f"expected {want_value:.6f}"],
                    "Read the noise off the world rather than assuming 0.1.")

        return passed(name, f"reading {reading} from uniform puts "
                            f"{expected['top_probability']:.4f} on "
                            f"{expected['top']}, and the belief sums to 1")
    except NotImplementedError:
        return not_written_yet(name)
    except Exception as error:  # noqa: BLE001
        return crashed(name, error, verbose)


# ----------------------------------------------------------------------
# Task 4: the filter
# ----------------------------------------------------------------------


def check_filter_sequence(filter_sequence, verbose=False):
    """Check a filter_sequence(world, belief, actions, readings) implementation."""
    name = "filter_sequence"
    try:
        world = standard_maze()
        trajectory = fixture_trajectory()
        expected = EXPECTED["filter_fixture"]

        got = filter_sequence(world, world.uniform_belief(),
                              trajectory.actions, trajectory.readings)
        if not isinstance(got, (list, tuple)):
            return failed(
                name,
                [f"it returned a {type(got).__name__}, not a list of beliefs"],
                "Collect the beliefs in a list as you go and return it.")

        if len(got) != expected["length"]:
            return failed(
                name,
                [f"it returned {len(got)} beliefs for "
                 f"{len(trajectory.actions)} actions and "
                 f"{len(trajectory.readings)} readings, "
                 f"expected {expected['length']}"],
                "One belief per reading, the first one included: the belief "
                "after reading 0 but before any action, then one after each "
                "action-and-reading pair.")

        for index, belief in enumerate(got):
            problems = belief_problems(world, belief, f"belief {index}")
            if problems:
                return failed(name, problems,
                              "Each entry should be the kind of dictionary "
                              "update returns.")
            if not sums_to_one(belief):
                return failed(
                    name,
                    [f"belief {index} adds up to {sum(belief.values()):.6f}, "
                     "not 1"],
                    "If update and predict both pass their checks, the only "
                    "way to break this is to feed one of them something it "
                    "did not expect.")

        first = got[0]
        top = max(sorted(first), key=lambda place: first[place])
        if (top != expected["first_top"]
                or abs(first[top] - expected["first_top_probability"]) > TOLERANCE):
            return failed(
                name,
                ["the first belief should be the uniform belief updated on "
                 f"reading 0 alone: {expected['first_top']} at "
                 f"{expected['first_top_probability']:.6f}.",
                 f"yours has {top} at {first[top]:.6f}",
                 f"your top cells: {describe_top(first)}"],
                "The robot takes a reading before it moves, so the run starts "
                "with an update, not a predict. Nothing has moved yet at t=0.")

        for t, (belief, want_cell, want_truth) in enumerate(
                zip(got, expected["map_cells"], expected["p_truth"])):
            best = max(sorted(belief), key=lambda place: belief[place])
            here = trajectory.cells[t]
            if abs(belief[here] - want_truth) > TOLERANCE:
                lines = []
                if best != want_cell:
                    lines.append(
                        f"at t = {t} your best guess is {best} "
                        f"({belief[best]:.4f}), but it should be {want_cell}.")
                lines += [
                    f"at t = {t} the robot is in {here}, and the belief "
                    f"should put {want_truth:.6f} there, not "
                    f"{belief[here]:.6f}.",
                    f"your top cells: {describe_top(belief)}",
                ]
                if t > 0:
                    lines.append(
                        f"everything up to t = {t - 1} was right, so look at "
                        "which action and which reading step " + str(t) +
                        " uses.")
                return failed(
                    name, lines,
                    "Each step is a predict on the action followed by an "
                    "update on the reading, in that order, with action "
                    "t - 1 paired with reading t. Performing them in the "
                    "other order, or pairing the wrong reading, goes wrong "
                    "here first.")

        return passed(name, f"{len(got)} beliefs, correct at every step; "
                            f"by t = {len(got) - 1} it puts "
                            f"{expected['p_truth'][-1]:.3f} on the truth")
    except NotImplementedError:
        return not_written_yet(name)
    except Exception as error:  # noqa: BLE001
        return crashed(name, error, verbose)


# ----------------------------------------------------------------------
# Task 5: the most likely path (second notebook)
# ----------------------------------------------------------------------


def path_log_probability(world, belief, actions, readings, path):
    """log P(this exact path and these readings), given the actions.

    The score ``viterbi_path`` is supposed to maximize. Returns -inf for a
    path the robot could not have taken, or one a reading rules out entirely.
    """
    def log(value):
        return -math.inf if value <= 0.0 else math.log(value)

    if len(path) != len(readings):
        raise ValueError(f"a path over {len(readings)} readings needs "
                         f"{len(readings)} cells, not {len(path)}")

    epsilon = world.epsilon
    def beam_likelihood(reading, cell):
        value = 1.0
        for observed, actual in zip(reading, world.signature(cell)):
            value *= (1.0 - epsilon) if observed == actual else epsilon
        return value

    total = log(belief[path[0]]) + log(beam_likelihood(readings[0], path[0]))
    for t, action in enumerate(actions):
        total += log(world.transition(path[t], action).get(path[t + 1], 0.0))
        total += log(beam_likelihood(readings[t + 1], path[t + 1]))
    return total


def check_viterbi_path(viterbi_path, verbose=False):
    """Check a viterbi_path(world, belief, actions, readings) implementation."""
    name = "viterbi_path"
    try:
        world = standard_maze()
        trajectory = fixture_trajectory()
        belief = world.uniform_belief()
        want_score = EXPECTED["viterbi_fixture"]["log_probability"]

        got = viterbi_path(world, belief, trajectory.actions,
                           trajectory.readings)
        if not isinstance(got, (list, tuple)):
            return failed(
                name,
                [f"it returned a {type(got).__name__}, not a list of cells"],
                "Return the cells of the best path, earliest first.")
        if len(got) != len(trajectory.readings):
            return failed(
                name,
                [f"it returned {len(got)} cells for "
                 f"{len(trajectory.readings)} readings"],
                "One cell per time step, the starting cell included.")

        outside = [place for place in got if tuple(place) not in set(world.cells)]
        if outside:
            return failed(
                name,
                [f"these are not free cells of the maze: {outside[:3]}"],
                "Every step of the path has to be somewhere the robot could be.")
        got = [tuple(place) for place in got]

        score = path_log_probability(world, belief, trajectory.actions,
                                     trajectory.readings, got)
        if score == -math.inf:
            broken = []
            for t in range(len(got) - 1):
                if got[t + 1] not in world.transition(got[t],
                                                      trajectory.actions[t]):
                    broken.append((t, got[t], got[t + 1]))
            lines = ["the path you returned has probability 0."]
            if broken:
                t, here, there = broken[0]
                lines.append(f"at t = {t} it goes from {here} to {there}, "
                             f"which action '{trajectory.actions[t]}' cannot do.")
                lines.append("that is what the sequence of per-step best "
                             "guesses looks like, and it is exactly what "
                             "this task is for.")
            return failed(
                name, lines,
                "The path has to hold together: each cell must be reachable "
                "from the one before it. Carry a backpointer saying which "
                "predecessor gave each cell its best score, and follow those "
                "back from the end.")

        if score < want_score - 1e-6:
            return failed(
                name,
                [f"your path scores {score:.4f}, but there is a path scoring "
                 f"{want_score:.4f}, so yours is not the most likely one.",
                 f"yours starts {got[:4]}"],
                "A path that is legal but not optimal usually means the "
                "maximum is being taken in the wrong place: at each step, "
                "each cell keeps the best score over its possible "
                "predecessors, and nothing is thrown away until the end.")
        if score > want_score + 1e-6:
            return failed(
                name,
                [f"your path scores {score:.4f}, which beats the reference "
                 f"score of {want_score:.4f}. Something is being counted "
                 "twice, or a factor is missing."],
                "Score a path by multiplying the prior on its first cell, "
                "each move's probability, and each reading's likelihood. "
                "Check against lab5kit.checks.path_log_probability.")

        return passed(name, f"a legal path scoring {score:.4f}, "
                            "which is the best there is")
    except NotImplementedError:
        return not_written_yet(name)
    except Exception as error:  # noqa: BLE001
        return crashed(name, error, verbose)


# ----------------------------------------------------------------------
# everything at once
# ----------------------------------------------------------------------


def check_all(sensor_likelihood=None, predict=None, update=None,
              filter_sequence=None, viterbi_path=None, verbose=False):
    """Run every check whose function is passed in, and summarize."""
    jobs = [
        ("sensor_likelihood", sensor_likelihood, check_sensor_likelihood),
        ("predict", predict, check_predict),
        ("update", update, check_update),
        ("filter_sequence", filter_sequence, check_filter_sequence),
        ("viterbi_path", viterbi_path, check_viterbi_path),
    ]
    results = {}
    for label, function, check in jobs:
        if function is None:
            continue
        results[label] = check(function, verbose=verbose)
    done = sum(1 for value in results.values() if value)
    print(f"\n{done} of {len(results)} checks passing.")
    return results
